### PR TITLE
BUG: use normalized_data.min() and .max()

### PR DESCRIPTION
**Pull request by aflaxman**
This works better for me.

### CODE REVIEW

**Comment by mstimberg** [comment]
Ugh, many thanks for making me aware of this, this must have slipped in during some late-night search&replace...

I think for consistency with the rest of the code I'd prefer:

``` Python
assert numpy.min(normalized_data) == 0.0
```

over

``` Python
assert normalized_data.min() == 0.0
```

though. I'll make the change.

Thanks again!

**Comment by mstimberg** [comment]
This should be fixed with commit 7d764eb -- please do not hesitate to open another pull request/issue if you find anything else that does not work or needs improvement.

**Comment by aflaxman** [comment]
Cool, that works for me, too.  Thanks for you for creating this lesson!  I did the testing portion yesterday for a small group and it worked well.  Next time I do it, I think I'll start with a real example of why I need tests as motivation.

**Comment by mstimberg** [comment]
Thanks for the feedback. Maybe the following repository can be a source of inspiration, the Powerpoint/PDF has a slide on "software bugs in research": https://github.com/ASPP/testing_debugging_profiling (in general their lesson covers a few aspects that I did not include, mostly due to lack of time -- in their schedule, a full day was scheduled for testing/debugging/profiling).

**Comment by aflaxman** [comment]
very nice, thanks!

**Pull request closed without merging**
